Repository boostcampwm-2022/android08-KiwiTalk, pull requests merged in 2022-12, with the labels that each got.

#87 채팅방 검색 화면 리팩토링, 키워드 검색 화면과 데이터 연동, 마커 정보 표시 제거
  app/src/main/java/com/kiwi/kiwitalk/model/ClusterMarker.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/search/SearchChatMapFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/search/SearchChatMapViewModel.kt
  data/src/main/java/com/kiwi/data/repository/SearchChatRepositoryImpl.kt
  domain/src/main/java/com/kiwi/domain/repository/SearchChatRepository.kt
Labels: feat

#88 코드 리펙토링 & 세부 기능 추가
  app/src/main/java/com/kiwi/kiwitalk/ChangeExpansion.kt
  app/src/main/java/com/kiwi/kiwitalk/Const.kt
  app/src/main/java/com/kiwi/kiwitalk/Util.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/newchat/NewChatFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/newchat/NewChatViewModel.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/newchat/SearchPlaceFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/newchat/SearchPlaceViewModel.kt
  app/src/main/res/drawable/ic_add_location.xml
  app/src/main/res/drawable/ic_add_photo.xml
  app/src/main/res/drawable/ic_location_on_.xml
  app/src/main/res/drawable/ic_location_on_click.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/fragment_new_chat.xml
  app/src/main/res/layout/fragment_search_place.xml
  app/src/main/res/menu/menu_search_chat_map.xml
  app/src/main/res/navigation/new_chat_nav_graph.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/kiwi/data/datasource/remote/NewChatRemoteDataSource.kt
  data/src/main/java/com/kiwi/data/datasource/remote/NewChatRemoteDataSourceImpl.kt
  data/src/main/java/com/kiwi/data/mapper/Mapper.kt
  data/src/main/java/com/kiwi/data/model/remote/NewChatRemote.kt
  data/src/main/java/com/kiwi/data/repository/NewChatRepositoryImpl.kt
  data/src/main/java/com/kiwi/data/repository/SearchPlaceRepositoryImpl.kt
  domain/src/main/java/com/kiwi/domain/model/NewChatInfo.kt
  domain/src/main/java/com/kiwi/domain/model/PlaceInfo.kt
  domain/src/main/java/com/kiwi/domain/model/PlaceInfoList.kt
  domain/src/main/java/com/kiwi/domain/model/PlaceList.kt
  domain/src/main/java/com/kiwi/domain/repository/NewChatRepository.kt
  domain/src/main/java/com/kiwi/domain/repository/SearchPlaceRepository.kt
Labels: 리뷰완료, feat

#95 [키워드화면]ui 개선, 초기화 시점 개선
  app/src/main/java/com/kiwi/kiwitalk/ui/keyword/SearchKeywordFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/keyword/SearchKeywordViewModel.kt
  app/src/main/res/layout/fragment_search_keyword.xml
  app/src/main/res/layout/item_keywordcategory.xml
Labels: 리뷰완료

#92 채팅방 검색 화면에 선택한 키워드 표시
  app/src/debug/res/layout/layout_map_fragment_dummy.xml
  app/src/main/java/com/kiwi/kiwitalk/ui/search/SearchChatMapFragment.kt
  app/src/main/res/layout/fragment_search_chat_map.xml
  app/src/main/res/values/strings.xml
Labels: feat

#96 채팅방 생성 방법 변경
  app/src/main/java/com/kiwi/kiwitalk/ui/newchat/NewChatFragment.kt
  data/src/main/java/com/kiwi/data/Const.kt
  data/src/main/java/com/kiwi/data/datasource/remote/NewChatRemoteDataSourceImpl.kt
  data/src/main/java/com/kiwi/data/mapper/DateFormatter.kt
  data/src/main/java/com/kiwi/data/mapper/Mapper.kt
Labels: feat

#103 fix: 채팅방 목록 불러올 때 목록이 여러번 그려지는 버그 수정
  app/src/main/java/com/kiwi/kiwitalk/ui/home/ChatListViewAdapter.kt
Labels: bug

#108 장소 검색 버그 수정 & 네트워크 상태 체크 & 툴바 기능 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kiwi/kiwitalk/NetworkStateManager.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/newchat/NewChatFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/newchat/SearchPlaceFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/newchat/SearchPlaceViewModel.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/search/SearchChatMapViewModel.kt
  app/src/main/java/com/kiwi/kiwitalk/util/ChangeExpansion.kt
  app/src/main/res/layout/fragment_new_chat.xml
  app/src/main/res/layout/fragment_search_place.xml
  app/src/main/res/menu/menu_new_chat.xml
  data/src/main/java/com/kiwi/data/datasource/remote/NewChatRemoteDataSource.kt
Labels: feat, bugfix

#106 채팅방 목록 UI 수정 및 기능 추가
  app/src/main/java/com/kiwi/kiwitalk/di/RepositoryModule.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/BindingAdapter.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/home/ChatListFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/home/ChatListViewAdapter.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/home/ChatListViewModel.kt
  app/src/main/java/com/kiwi/kiwitalk/util/Const.kt
  app/src/main/res/drawable/bg_chat_list_unread_count.xml
  app/src/main/res/layout/item_chat_list.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/kiwi/data/datasource/remote/ExitChatRemoteDataSource.kt
  data/src/main/java/com/kiwi/data/datasource/remote/ExitChatRemoteDataSourceImpl.kt
  data/src/main/java/com/kiwi/data/repository/ExitChatRepositoryImpl.kt
  domain/src/main/java/com/kiwi/domain/repository/ExitChatRepository.kt
Labels: feat

#122 [키워드화면]키워드 선택 후 백버튼(뒤로가기) 클릭시 선택된 키워드 저장 버그 수정
  app/src/main/java/com/kiwi/kiwitalk/ui/keyword/SearchKeywordFragment.kt
Labels: 리뷰완료

#114 클러스터링 마커 커스텀 & 다크모드 대응
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kiwi/kiwitalk/NetworkStateManager.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/newchat/NewChatFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/newchat/SearchPlaceFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/search/ClusterMarkerRenderer.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/search/SearchChatMapFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/util/Util.kt
  app/src/main/res/drawable/background_marker_text.xml
  app/src/main/res/drawable/ic_location_cluster.xml
  app/src/main/res/drawable/ic_location_on.xml
  app/src/main/res/layout/fragment_new_chat.xml
  app/src/main/res/layout/item_marker.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  data/src/main/java/com/kiwi/data/datasource/remote/NewChatRemoteDataSourceImpl.kt
Labels: 리뷰완료, feat, refactor

#116 채팅방 검색 화면 기능 개선 & 버그 수정
  app/src/main/java/com/kiwi/kiwitalk/ui/search/SearchChatMapFragment.kt
  app/src/main/res/layout/fragment_search_chat_map.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/com/kiwi/data/datasource/remote/SearchChatRemoteDataSourceImpl.kt
  data/src/main/java/com/kiwi/data/repository/SearchChatRepositoryImpl.kt
Labels: feat, bugfix

#125 프로필 이미지 수정, 채팅방 이미지 추가 기능 구현
  app/build.gradle
  app/src/main/java/com/kiwi/kiwitalk/di/FirebaseModule.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/home/ProfileSettingFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/home/ProfileViewModel.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/newchat/NewChatFragment.kt
  data/build.gradle
  data/src/main/java/com/kiwi/data/datasource/remote/NewChatRemoteDataSourceImpl.kt
Labels: feat

#126 채팅방 목록 버그 수정
  app/src/main/java/com/kiwi/kiwitalk/ui/BindingAdapter.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/home/ChatListFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/util/Const.kt
Labels: bugfix

#131 fix: 채팅방 목록을 제대로 갱신하지 않는 문제 해결
  app/src/main/java/com/kiwi/kiwitalk/ui/home/ChatListFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/home/ChatListViewAdapter.kt
Labels: 리뷰완료, feat

#147 채팅방 검색 화면 기능 수정
  app/src/main/java/com/kiwi/kiwitalk/ui/search/SearchChatMapFragment.kt
  app/src/main/java/com/kiwi/kiwitalk/ui/search/SearchChatMapViewModel.kt
  data/src/main/java/com/kiwi/data/datasource/remote/SearchChatRemoteDataSourceImpl.kt
Labels: feat

#151 refactor: 하드 코딩 된 주소 필터 수정
  chatmapper/src/main/java/com/kiwi/chatmapper/ChatConst.kt
  chatmapper/src/main/java/com/kiwi/chatmapper/ChatMapper.kt
Labels: feat
